# Generated by Django 4.2.7 on 2024-09-12 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('StakeHolders', '0008_alter_teacher_web_push_subscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.TextField()),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('student', models.ManyToManyField(blank=True, to='StakeHolders.student')),
            ],
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('mcq', 'Multiple Choices'), ('desc', 'Descriptive')], default='mcq', max_length=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('allowed_students', models.ManyToManyField(blank=True, to='StakeHolders.student')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='StakeHolders.teacher')),
                ('options', models.ManyToManyField(blank=True, to='AdditionalFeatures.surveyoption')),
            ],
        ),
    ]
