# Generated by Django 4.2.7 on 2024-09-12 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdditionalFeatures', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='survey',
            old_name='created_by',
            new_name='owner',
        ),
    ]
