# Generated by Django 4.2.7 on 2024-09-14 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdditionalFeatures', '0003_studymaterial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyMaterial_Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField()),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='studymaterial',
            name='link',
        ),
        migrations.AddField(
            model_name='studymaterial',
            name='links',
            field=models.ManyToManyField(blank=True, to='AdditionalFeatures.studymaterial_link'),
        ),
    ]
