# Generated by Django 4.2.7 on 2024-09-14 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdditionalFeatures', '0004_studymaterial_link_remove_studymaterial_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studymaterial_link',
            name='filename',
            field=models.TextField(blank=True),
        ),
    ]
