# Generated by Django 4.2.7 on 2024-02-10 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Manage', '0018_term_status'),
        ('StakeHolders', '0002_student_sr_no'),
        ('Session', '0002_alter_attendance_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StakeHolders.student'),
        ),
        migrations.AlterField(
            model_name='session',
            name='lecture',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Manage.lecture'),
        ),
    ]
