# Generated by Django 4.2.7 on 2024-02-11 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Session', '0003_alter_attendance_student_alter_session_lecture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='session',
            old_name='status',
            new_name='active',
        ),
    ]
