# Generated by Django 4.2.7 on 2024-02-12 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Session', '0004_rename_status_session_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='day',
            field=models.DateField(blank=True, null=True),
        ),
    ]
