# Generated by Django 4.2.7 on 2024-02-12 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Session', '0005_session_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='active',
            field=models.CharField(blank=True, choices=[('pre', 'Pre'), ('ongoing', 'Ongoing'), ('post', 'Post')], max_length=7, null=True),
        ),
    ]
