# Generated by Django 4.2.7 on 2024-02-24 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Session', '0008_attendance_manual'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
