# Generated by Django 4.2.7 on 2024-02-24 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Session', '0009_attendance_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='latt',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='long',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='on_premises',
            field=models.BooleanField(default=False),
        ),
    ]
