# Generated by Django 4.2.7 on 2024-02-24 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Session', '0011_remove_attendance_marking_ip'),
    ]

    operations = [
        migrations.CreateModel(
            name='GPSCoordinates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('long', models.CharField(blank=True, max_length=255, null=True)),
                ('latt', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='latt',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='long',
        ),
        migrations.AddField(
            model_name='attendance',
            name='coordinates',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Session.gpscoordinates'),
        ),
        migrations.AddField(
            model_name='session',
            name='teacher_coordinates',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Session.gpscoordinates'),
        ),
    ]
