# Generated by Django 4.2.7 on 2024-02-25 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Manage', '0025_gpscoordinates_classroom_gps_coordinates'),
        ('Session', '0012_gpscoordinates_remove_attendance_latt_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='teacher_coordinates',
        ),
        migrations.AlterField(
            model_name='attendance',
            name='coordinates',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Manage.gpscoordinates'),
        ),
        migrations.DeleteModel(
            name='GPSCoordinates',
        ),
    ]
