# Generated by Django 4.2.7 on 2024-09-03 05:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('StakeHolders', '0008_alter_teacher_web_push_subscription'),
        ('Manage', '0028_alter_subject_code'),
        ('Session', '0013_remove_session_teacher_coordinates_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.TextField()),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('student', models.ManyToManyField(blank=True, to='StakeHolders.student')),
            ],
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('mcq', 'Multiple Choices'), ('desc', 'Descriptive')], default='mcq', max_length=4)),
                ('allowd_choices', models.CharField(choices=[('single', 'Single Choice'), ('multiple', 'Multiple Choice')], default='single', max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('active', models.CharField(blank=True, choices=[('pre', 'Pre'), ('ongoing', 'Ongoing'), ('post', 'Post')], max_length=7, null=True)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('lecture', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Manage.lecture')),
                ('options', models.ManyToManyField(blank=True, null=True, to='Session.surveyoption')),
            ],
        ),
    ]
