# Generated by Django 4.2.7 on 2024-09-03 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Session', '0014_surveyoption_survey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='survey',
            name='options',
            field=models.ManyToManyField(blank=True, to='Session.surveyoption'),
        ),
    ]
