# Generated by Django 4.2.7 on 2024-09-03 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StakeHolders', '0008_alter_teacher_web_push_subscription'),
        ('Session', '0015_alter_survey_active_alter_survey_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='allowed_students',
            field=models.ManyToManyField(blank=True, to='StakeHolders.student'),
        ),
    ]
