# Generated by Django 4.2.7 on 2024-09-12 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Session', '0016_survey_allowed_students'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surveyoption',
            name='student',
        ),
        migrations.DeleteModel(
            name='Survey',
        ),
        migrations.DeleteModel(
            name='SurveyOption',
        ),
    ]
