# Generated by Django 4.2.7 on 2024-02-07 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Manage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='division',
            name='semester',
        ),
        migrations.RemoveField(
            model_name='lecture',
            name='batches',
        ),
        migrations.RemoveField(
            model_name='lecture',
            name='classroom',
        ),
        migrations.RemoveField(
            model_name='lecture',
            name='schedule',
        ),
        migrations.RemoveField(
            model_name='lecture',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='lecture',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='timetable',
        ),
        migrations.RemoveField(
            model_name='semester',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='division',
        ),
        migrations.DeleteModel(
            name='Batch',
        ),
        migrations.DeleteModel(
            name='Division',
        ),
        migrations.DeleteModel(
            name='Lecture',
        ),
        migrations.DeleteModel(
            name='Schedule',
        ),
        migrations.DeleteModel(
            name='Semester',
        ),
        migrations.DeleteModel(
            name='TimeTable',
        ),
    ]
