# Generated by Django 4.2.7 on 2024-02-07 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('StakeHolders', '0001_initial'),
        ('Manage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='teachers',
            field=models.ManyToManyField(to='StakeHolders.teacher'),
        ),
        migrations.AddField(
            model_name='semester',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Manage.branch'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='timetable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Manage.timetable'),
        ),
        migrations.AddField(
            model_name='lecture',
            name='batches',
            field=models.ManyToManyField(to='Manage.batch'),
        ),
        migrations.AddField(
            model_name='lecture',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Manage.classroom'),
        ),
        migrations.AddField(
            model_name='lecture',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Manage.subject'),
        ),
        migrations.AddField(
            model_name='lecture',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StakeHolders.teacher'),
        ),
        migrations.AddField(
            model_name='division',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Manage.semester'),
        ),
        migrations.AddField(
            model_name='classroom',
            name='routers',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Manage.router'),
        ),
        migrations.AddField(
            model_name='branch',
            name='admins',
            field=models.ManyToManyField(to='StakeHolders.admin'),
        ),
        migrations.AddField(
            model_name='branch',
            name='college',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Manage.college'),
        ),
        migrations.AddField(
            model_name='batch',
            name='division',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Manage.division'),
        ),
        migrations.AddField(
            model_name='batch',
            name='students',
            field=models.ManyToManyField(to='StakeHolders.student'),
        ),
    ]
