# Generated by Django 4.2.7 on 2023-11-18 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TimeTable', '0001_initial'),
        ('Manage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='semester',
            name='time_table',
            field=models.ManyToManyField(blank=True, to='TimeTable.timetable'),
        ),
    ]
