# Generated by Django 4.2.7 on 2023-11-16 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manage', '0003_alter_college_branches'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='semesters',
            field=models.ManyToManyField(blank=True, to='Manage.semester'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='batches',
            field=models.ManyToManyField(blank=True, to='Manage.batch'),
        ),
        migrations.AlterField(
            model_name='semester',
            name='subjects',
            field=models.ManyToManyField(blank=True, to='Manage.subject'),
        ),
    ]
