# Generated by Django 4.2.7 on 2023-11-18 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Manage', '0003_branch_branch_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branch',
            name='branch_code',
        ),
    ]
