# Generated by Django 4.2.7 on 2024-02-07 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manage', '0004_remove_classroom_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
