# Generated by Django 4.2.7 on 2023-11-16 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Manage', '0004_alter_batch_semesters_alter_branch_batches_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='name',
            new_name='subject_name',
        ),
    ]
