# Generated by Django 4.2.7 on 2023-11-18 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manage', '0005_branch_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branch',
            name='code',
        ),
        migrations.AddField(
            model_name='branch',
            name='branch_code',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
