# Generated by Django 4.2.7 on 2023-11-16 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manage', '0005_rename_name_subject_subject_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedules', models.CharField(default='Not Set Yet', max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='semester',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='semester',
            name='time_table',
            field=models.ManyToManyField(blank=True, to='Manage.timetable'),
        ),
    ]
