# Generated by Django 4.2.7 on 2024-02-07 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manage', '0006_remove_router_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='router',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
