# Generated by Django 4.2.7 on 2023-11-16 13:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manage', '0006_timetable_semester_status_semester_time_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='semester',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2023, 11, 16, 13, 43, 53, 320881, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='semester',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2023, 11, 16, 13, 43, 57, 748295, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
