# Generated by Django 4.2.7 on 2023-11-18 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manage', '0006_remove_branch_code_branch_branch_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='branch_code',
            field=models.IntegerField(unique=True),
        ),
    ]
