# Generated by Django 4.2.7 on 2023-11-16 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manage', '0007_semester_end_date_semester_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='semester',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
