# Generated by Django 4.2.7 on 2024-02-07 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StakeHolders', '0001_initial'),
        ('Manage', '0008_alter_batch_students'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='students',
            field=models.ManyToManyField(blank=True, to='StakeHolders.student'),
        ),
    ]
