# Generated by Django 4.2.7 on 2023-11-23 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TimeTable', '0008_alter_lecture_end_time_alter_lecture_start_time'),
        ('Manage', '0008_batch_active_batch_end_year_batch_start_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='semester',
            name='time_table',
        ),
        migrations.AddField(
            model_name='semester',
            name='time_table',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='TimeTable.timetable'),
        ),
    ]
