# Generated by Django 4.2.7 on 2024-02-07 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Manage', '0009_alter_batch_students'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semester',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Manage.branch'),
        ),
    ]
