# Generated by Django 4.2.7 on 2023-11-17 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manage', '0011_alter_subject_credit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='code',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='credit',
            field=models.IntegerField(),
        ),
    ]
