# Generated by Django 4.2.7 on 2024-02-08 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StakeHolders', '0001_initial'),
        ('Manage', '0013_branch_students_branch_teachers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='admins',
            field=models.ManyToManyField(blank=True, to='StakeHolders.admin'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='students',
            field=models.ManyToManyField(blank=True, to='StakeHolders.student'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='teachers',
            field=models.ManyToManyField(blank=True, to='StakeHolders.teacher'),
        ),
    ]
