# Generated by Django 4.2.7 on 2024-02-09 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('StakeHolders', '0001_initial'),
        ('Manage', '0015_classroom_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='batches',
            field=models.ManyToManyField(blank=True, to='Manage.batch'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='classroom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Manage.classroom'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Manage.schedule'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Manage.subject'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='StakeHolders.teacher'),
        ),
    ]
