# Generated by Django 4.2.7 on 2024-02-09 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manage', '0017_remove_semester_branch_remove_semester_end_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='term',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
