# Generated by Django 4.2.7 on 2024-02-17 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manage', '0018_term_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classroom',
            old_name='routers',
            new_name='router',
        ),
        migrations.AddField(
            model_name='router',
            name='subnet_nask',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='router',
            name='network_add',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
