# Generated by Django 4.2.7 on 2024-02-17 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manage', '0020_remove_router_subnet_nask_router_cidr'),
    ]

    operations = [
        migrations.AddField(
            model_name='router',
            name='hostname',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
