# Generated by Django 4.2.7 on 2024-02-23 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Manage', '0021_router_hostname'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='is_proxy',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('from_lecture', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='from_links', to='Manage.lecture')),
                ('to_lecture', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='to_links', to='Manage.lecture')),
            ],
        ),
    ]
