# Generated by Django 4.2.7 on 2024-02-24 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manage', '0022_lecture_is_proxy_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
