# Generated by Django 4.2.7 on 2024-02-27 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manage', '0025_gpscoordinates_classroom_gps_coordinates'),
    ]

    operations = [
        migrations.AddField(
            model_name='gpscoordinates',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
