# Generated by Django 4.2.7 on 2024-02-29 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manage', '0026_gpscoordinates_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='branch_code',
            field=models.CharField(blank=True, max_length=3, null=True, unique=True),
        ),
    ]
