# Generated by Django 4.2.7 on 2024-09-14 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StakeHolders', '0009_superadmin'),
        ('Manage', '0029_subject_included_batches_term_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='super_admins',
            field=models.ManyToManyField(blank=True, to='StakeHolders.superadmin'),
        ),
    ]
