# Generated by Django 4.2.7 on 2023-11-18 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TimeTable', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='routers',
            field=models.ManyToManyField(blank=True, to='TimeTable.router'),
        ),
    ]
