# Generated by Django 4.2.7 on 2023-11-20 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TimeTable', '0004_alter_lecture_classroom_alter_lecture_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='end_time',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='start_time',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
