# Generated by Django 4.2.7 on 2023-11-20 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TimeTable', '0005_alter_lecture_end_time_alter_lecture_start_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='lecutres',
            new_name='lectures',
        ),
    ]
