# Generated by Django 4.2.7 on 2023-11-20 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('StakeHolders', '0001_initial'),
        ('TimeTable', '0006_rename_lecutres_schedule_lectures'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='StakeHolders.teacher'),
        ),
    ]
