# Generated by Django 4.2.7 on 2024-02-09 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StakeHolders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='sr_no',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
    ]
