# Generated by Django 4.2.7 on 2023-11-22 07:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Manage', '0008_batch_active_batch_end_year_batch_start_year'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('StakeHolders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment', models.IntegerField(max_length=12)),
                ('display_picture', models.URLField()),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Manage.branch')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('subjects', models.ManyToManyField(blank=True, to='Manage.subject')),
            ],
        ),
    ]
