# Generated by Django 4.2.7 on 2023-11-16 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manage', '0002_alter_batch_semesters_alter_branch_batches_and_more'),
        ('StakeHolders', '0002_admin_branch_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='subjects',
            field=models.ManyToManyField(to='Manage.subject'),
        ),
    ]
