# Generated by Django 4.2.7 on 2024-02-28 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StakeHolders', '0002_student_sr_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='sr_no',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
