# Generated by Django 4.2.7 on 2023-11-22 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StakeHolders', '0003_alter_student_enrollment'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
