# Generated by Django 4.2.7 on 2023-11-16 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manage', '0004_alter_batch_semesters_alter_branch_batches_and_more'),
        ('StakeHolders', '0003_alter_teacher_subjects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='subjects',
            field=models.ManyToManyField(blank=True, to='Manage.subject'),
        ),
    ]
