# Generated by Django 4.2.7 on 2024-03-04 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StakeHolders', '0003_alter_student_sr_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='web_push_subscription',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
