# Generated by Django 4.2.7 on 2023-11-22 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StakeHolders', '0004_student_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='enrollment',
            field=models.CharField(max_length=12, unique=True),
        ),
    ]
