# Generated by Django 4.2.7 on 2023-11-22 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StakeHolders', '0005_alter_student_enrollment'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='thank_you_response',
            field=models.TextField(blank=True, null=True),
        ),
    ]
