# Generated by Django 4.2.7 on 2024-03-08 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StakeHolders', '0005_alter_student_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationSubscriptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription', models.JSONField()),
            ],
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='web_push_subscription',
        ),
        migrations.AddField(
            model_name='teacher',
            name='web_push_subscription',
            field=models.ManyToManyField(to='StakeHolders.notificationsubscriptions'),
        ),
    ]
