# Generated by Django 4.2.7 on 2024-03-09 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StakeHolders', '0006_notificationsubscriptions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationsubscriptions',
            name='subscription',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='web_push_subscription',
            field=models.ManyToManyField(blank=True, null=True, to='StakeHolders.notificationsubscriptions'),
        ),
    ]
