# Generated by Django 4.2.7 on 2023-11-22 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StakeHolders', '0006_student_thank_you_response'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='steps',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
