# Generated by Django 4.2.7 on 2023-11-22 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Manage', '0008_batch_active_batch_end_year_batch_start_year'),
        ('StakeHolders', '0009_alter_student_steps'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='semester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Manage.semester'),
        ),
    ]
