# Generated by Django 4.2.7 on 2024-09-15 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StakeHolders', '0009_superadmin'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationsubscriptions',
            name='type',
            field=models.CharField(blank=True, choices=[('lectures', 'Lectures'), ('alerts', 'Alerts')], max_length=10, null=True),
        ),
    ]
