# Generated by Django 4.2.7 on 2023-11-23 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StakeHolders', '0010_student_semester'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='display_picture',
            new_name='signature_link',
        ),
    ]
