# Generated by Django 4.2.7 on 2024-09-15 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StakeHolders', '0010_notificationsubscriptions_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='web_push_subscription',
            field=models.ManyToManyField(blank=True, to='StakeHolders.notificationsubscriptions'),
        ),
        migrations.AddField(
            model_name='student',
            name='web_push_subscription',
            field=models.ManyToManyField(blank=True, to='StakeHolders.notificationsubscriptions'),
        ),
    ]
