# Generated by Django 4.2.7 on 2024-09-15 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StakeHolders', '0011_admin_web_push_subscription_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notificationsubscriptions',
            old_name='type',
            new_name='subscription_type',
        ),
    ]
