# Generated by Django 4.2.7 on 2023-11-23 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StakeHolders', '0011_rename_display_picture_student_signature_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='signature_link',
            field=models.TextField(blank=True, null=True),
        ),
    ]
