# Generated by Django 4.2.7 on 2024-09-14 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Notifications', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='descripiton',
            new_name='description',
        ),
    ]
