# Generated by Django 4.2.7 on 2024-09-14 11:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notifications', '0002_rename_descripiton_event_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 9, 14, 11, 24, 46, 480257, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
